<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0-android36.1;net10.0-ios26.5</TargetFrameworks>
		<AssemblyName>ZXingNetMobile</AssemblyName>
		<RootNamespace>ZXing.Net.Mobile</RootNamespace>
		<PackageId>db2222.ZXing.Net.Mobile</PackageId>
		<PackageIcon>icon.png</PackageIcon>
		<Summary>ZXing Barcode Scanning for your .NET Android &amp; iOS apps</Summary>
		<PackageTags></PackageTags>
		<Title>ZXing.Net.Mobile Barcode Scanner (db2222 Fork)</Title>
		<Description>
			ZXing.Net.Mobile is a C#/.NET library based on the open source Barcode Library: ZXing (Zebra Crossing), using the ZXing.Net Port. It works with .NET for Android &amp; iOS. The goal of ZXing.Net.Mobile is to make scanning barcodes as effortless and painless as possible in your own applications.

			The original project is https://github.com/Redth/ZXing.Net.Mobile.
			It is dead and the successor is https://github.com/Redth/ZXing.Net.MAUI.
			But if you use .NET Android or iOS instead of MAUI you can't use it.
			This project is a fork to switch to modern .NET Android/iOS with necessary bugfixes.
			It is forked from the fork https://github.com/Respawnsive/ZXing.Net.Mobile to have the mentioned fix from https://github.com/Redth/ZXing.Net.Mobile/issues/924#issuecomment-1430058104.
		</Description>
		<Product>$(AssemblyName) ($(TargetFramework))</Product>
		<Version>3.0.1</Version>
		<PackageVersion>$(Version)$(VersionSuffix)</PackageVersion>
		<Authors>Redth, Respawnsive &amp; db2222</Authors>
		<Owners>Redth</Owners>
		<NeutralLanguage>en</NeutralLanguage>
		<Copyright>© Redth</Copyright>
		<RepositoryUrl>https://github.com/db2222/ZXing.Net.Mobile</RepositoryUrl>
		<PackageReleaseNotes>v3.0.1
- First release after .NET modernization

See https://github.com/Redth/ZXing.Net.Mobile/releases for the orignal ones.</PackageReleaseNotes>
		<DefineConstants>$(DefineConstants);</DefineConstants>
		<UseFullSemVerForNuGet>false</UseFullSemVerForNuGet>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/db2222/ZXing.Net.Mobile</PackageProjectUrl>
		<DebugType>portable</DebugType>
		<Configurations>Debug;Release</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\Art\ZXing.Net.Mobile-Icon.png" PackagePath="icon.png" Pack="true" />
		<Compile Include="**\*.shared.cs" />
		<Compile Include="**\*.shared.*.cs" />
	</ItemGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('netstandard')) ">
		<Compile Include="**\*.netstandard.cs" />
		<Compile Include="**\*.netstandard.*.cs" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="Android\**\*.android.cs" Visible="false" />
		<Compile Include="Android\**\*.android.*.cs" Visible="false" />
		<Compile Include="iOS\**\*.ios.cs" Visible="false" />
		<Compile Include="iOS\**\*.ios.*.cs" Visible="false" />
		<AndroidResource Include="Resources\layout\*.axml" Visible="false" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Android\**\*" Visible="true" />
		<None Include="iOS\**\*" Visible="true" />
		<None Include="Resources\**\*" Visible="true" />
	</ItemGroup>
	<ItemGroup Condition=" !$(TargetFramework.StartsWith('net10.0-android')) ">
		<Compile Remove="Android\**\*.android.cs" />
		<Compile Remove="Android\**\*.android.*.cs" />
		<AndroidResource Remove="Resources\**\*.axml" />
	</ItemGroup>
	<ItemGroup Condition=" !$(TargetFramework.StartsWith('net10.0-ios')) ">
		<Compile Remove="iOS\**\*.ios.cs" />
		<Compile Remove="iOS\**\*.ios.*.cs" />
	</ItemGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('net10.0-android')) ">
		<PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.4" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.90" />
		<PackageReference Include="ZXing.Net" Version="0.16.11" />
	</ItemGroup>
</Project>