<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0-android36.1;net10.0-ios26.5</TargetFrameworks>
		<AssemblyName>ZXingNetMobile</AssemblyName>
		<RootNamespace>ZXing.Net.Mobile</RootNamespace>
		<PackageId>Respawnsive.ZXing.Net.Mobile</PackageId>
		<PackageIcon>icon.png</PackageIcon>
		<Summary>ZXing Barcode Scanning for your .NET Android &amp; iOS apps</Summary>
		<PackageTags></PackageTags>
		<Title>ZXing.Net.Mobile Barcode Scanner (Respawnsive Fork)</Title>
		<Description>
			ZXing.Net.Mobile is a C#/.NET library based on the open source Barcode Library: ZXing (Zebra Crossing), using the ZXing.Net Port. It works with .NET for Android &amp; iOS. The goal of ZXing.Net.Mobile is to make scanning barcodes as effortless and painless as possible in your own applications.

			See https://github.com/Redth/ZXing.Net.Mobile/releases for release notes.
		</Description>
		<Product>$(AssemblyName) ($(TargetFramework))</Product>
		<AssemblyVersion>3.0.0.0</AssemblyVersion>
		<AssemblyFileVersion>3.0.0.0</AssemblyFileVersion>
		<Version>3.0.0</Version>
		<PackageVersion>$(Version)$(VersionSuffix)</PackageVersion>
		<Authors>Redth</Authors>
		<Owners>Redth</Owners>
		<NeutralLanguage>en</NeutralLanguage>
		<Copyright>© Redth</Copyright>
		<RepositoryUrl>https://github.com/redth/ZXing.Net.Mobile</RepositoryUrl>
		<PackageReleaseNotes>See: https://github.com/Redth/ZXing.Net.Mobile/releases</PackageReleaseNotes>
		<DefineConstants>$(DefineConstants);</DefineConstants>
		<UseFullSemVerForNuGet>false</UseFullSemVerForNuGet>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>http://github.com/Redth/ZXing.Net.Mobile</PackageProjectUrl>
		<DebugType>portable</DebugType>
		<Configurations>Debug;Release</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\Art\ZXing.Net.Mobile-Icon.png" PackagePath="icon.png" Pack="true" />
		<Compile Include="**\*.shared.cs" />
		<Compile Include="**\*.shared.*.cs" />
	</ItemGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('netstandard')) ">
		<Compile Include="**\*.netstandard.cs" />
		<Compile Include="**\*.netstandard.*.cs" />
	</ItemGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('net10.0-android')) ">
		<Compile Include="**\*.android.cs" />
		<Compile Include="**\*.android.*.cs" />
		<AndroidResource Include="Resources\layout\*.axml" />
		<PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.4" />
	</ItemGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('net10.0-ios')) ">
		<Compile Include="**\*.ios.cs" />
		<Compile Include="**\*.ios.*.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.80" />
		<PackageReference Include="ZXing.Net" Version="0.16.11" />
	</ItemGroup>
</Project>